version: "3.4"

services:
  dev:
    # personal docker registry, you need to docker-login to access.
    image: registry.23alice.duckdns.org/dev:latest
    build:
      context: ./
      dockerfile: docker/Dockerfile
      network: host